Failed TC
newscorp-ghfb/panda-qa pull request #142
Opened 2024-10-23 15:04 UTC by JansiSasiumar12

2024-10-23 15:26 UTC, ArchanaSaini149 requested changes
Please review the comments, fix them and re-submit. Thank you !

2024-10-23 15:26 UTC, ArchanaSaini149 commented on panda-qa/Resources/DefinedKeywords.robot
We dont need TC for Table alignment. That was a manual task. Please remove this code form Automation.

2024-10-23 15:26 UTC, ArchanaSaini149 commented on panda-qa/Resources/PageObjects/BarronsWatchlistPage.robot
Remove "r" from first line.

2024-10-23 15:26 UTC, ArchanaSaini149 commented on panda-qa/Resources/PageObjects/BarronsWatchlistPage.robot
remove method "Validate Table Alignment". We dont need automation for table alignment

2024-10-23 15:26 UTC, ArchanaSaini149 commented on panda-qa/Tests/FollowWidget/Regression/Barrons_Regression.robot
remove automation for #US-4049. We dont need automation for Table alignment

2024-10-24 13:24 UTC, JansiSasiumar12 commented
OK. I will correct and submitted

2024-10-24 13:24 UTC, closed without merging

2024-10-24 13:25 UTC, JansiSasiumar12 commented
Resubmitted